<?php
session_start();
require_once dirname(__DIR__, 2) . '/includes/auditoria.php';
orionRegistrarAtividade();
if (!isset($_SESSION['usuario_id'])) { header('Location: ../../index.php'); exit; }
$tipo = basename(__FILE__, '.php');
$arquivo = dirname(__DIR__, 2) . '/data/colaboradores/' . ($tipo === 'inativos' ? 'inativos.json' : 'terceiros.json');
$lista = json_decode(file_get_contents($arquivo), true) ?: [];
$titulo = $tipo === 'inativos' ? 'Colaboradores inativos' : 'Terceiros';
?>
<!doctype html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo $titulo; ?> - Orion Inventory</title><link rel="stylesheet" href="../../assets/css/global/import.css"><link rel="stylesheet" href="../../assets/css/pages/dashboard.css"><link rel="stylesheet" href="../../assets/css/pages/colaboradores.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"></head><body><header><nav class="menu-lateral"><div class="btn-expandir"><i class="bi bi-card-list"></i></div><ul><li class="item-menu active"><a href="colaboradores.php"><span class="item"><i class="bi bi-person"></i></span><span class="txt-link">Colaboradores</span></a></li></ul></nav><div class="logo"><a href="../dashbord/dashbord.php"><img src="../../img/global/logos/orion" alt="Orion Inventory"></a></div><div class="usuario-menu"><span class="usuario-nome"><i class="fas fa-user-shield"></i> <?php echo htmlspecialchars($_SESSION['usuario_nome'] ?? 'Usuário'); ?></span></div><a href="../../logout.php" class="sair-btn"><i class="fas fa-sign-out-alt"></i><span>Sair</span></a></header><main class="collaborators-page"><div class="page-title"><div><h1><i class="fas fa-users"></i> <?php echo $titulo; ?></h1><p>Registros separados dos colaboradores ativos</p></div><a class="secondary-action" href="colaboradores.php"><i class="fas fa-arrow-left"></i> Colaboradores</a></div><section class="collaborators-card"><div class="table-heading"><h2><i class="fas fa-list"></i> <?php echo $titulo; ?></h2></div><div class="collaborators-table-wrap"><table><thead><tr><th>Nome</th><th>CPF</th><th>Departamento</th><th>E-mail</th></tr></thead><tbody><?php if (!$lista): ?><tr><td colspan="4" class="empty-row">Nenhum registro encontrado.</td></tr><?php else: foreach ($lista as $item): ?><tr><td><strong><?php echo htmlspecialchars($item['nome'] ?? ''); ?></strong></td><td><?php echo htmlspecialchars($item['cpf'] ?? '—'); ?></td><td><?php echo htmlspecialchars($item['departamento'] ?? '—'); ?></td><td><?php echo htmlspecialchars($item['email'] ?? '—'); ?></td></tr><?php endforeach; endif; ?></tbody></table></div></section></main><footer><p>Orion Inventory © 2023 - 2026 - Todos os direitos reservados</p></footer></body></html>
