<?php
function gerarDocumentoTermo(array $colaborador, array $equipamentos, array $linhas, string $tipo, string $observacoes, string $local, string $base): string {
    $titulo = $tipo === 'entrega' ? 'Termo de responsabilidade pela guarda e uso de equipamento de trabalho' : 'Termo de devolução de equipamento';
    $logoPath = $base . '/img/pages/termos/amorsaude.jpg';
    $logo = is_file($logoPath) ? 'data:image/jpeg;base64,' . base64_encode(file_get_contents($logoPath)) : '';
    $css = file_get_contents($base . '/assets/css/pages/termo-documento.css');
    $cpf = preg_replace('/\D/', '', (string)($colaborador['cpf'] ?? ''));
    if (strlen($cpf) === 11) $cpf = substr($cpf, 0, 3) . '.' . substr($cpf, 3, 3) . '.' . substr($cpf, 6, 3) . '-' . substr($cpf, 9);
    ob_start(); ?>
<!doctype html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= h($titulo . ' - ' . $colaborador['nome']) ?></title><style><?= $css ?></style></head><body>
<div class="document-toolbar"><button type="button" onclick="window.print()">Imprimir / salvar em PDF</button><a href="termos.php?colaborador_id=<?= h($colaborador['id']) ?>">Voltar para termos</a></div>
<main class="term-document"><?php if ($logo): ?><img class="term-logo" src="<?= h($logo) ?>" alt="AmorSaúde"><?php endif; ?><h1><?= h($titulo) ?></h1><h2>Identificação do colaborador</h2><div class="term-identity"><?php foreach (['nome' => 'Nome', 'cargo' => 'Função', 'matricula' => 'Matrícula', 'departamento' => 'Departamento', 'centro_custo' => 'Centro de custo', 'email' => 'E-mail'] as $campo => $rotulo): ?><p><strong><?= $rotulo ?>:</strong> <?= h($colaborador[$campo] ?? '—') ?></p><?php endforeach; ?><p><strong>CPF:</strong> <?= h($cpf ?: '—') ?></p><p><strong>Data:</strong> <?= date('d/m/Y') ?></p></div>
<?php if ($tipo === 'entrega'): ?><p>Declaro que recebi os itens relacionados abaixo para uso nas atividades de trabalho e que conferi as informações e o estado dos equipamentos no momento da entrega.</p><ol><li>Comprometo-me a conservar os itens e utilizá-los de acordo com as orientações da empresa.</li><li>Comunicarei à área responsável ocorrências de dano, perda, defeito ou necessidade de manutenção.</li><li>Devolverei os itens quando solicitado, com seus acessórios, registrando as condições da devolução.</li></ol><?php else: ?><p>Declaro a devolução dos itens relacionados abaixo à área responsável. A conferência do recebimento e as condições dos equipamentos devem ser registradas neste termo.</p><?php endif; ?>
<h2><?= $tipo === 'entrega' ? 'Equipamentos entregues' : 'Equipamentos devolvidos' ?></h2>
<?php if ($equipamentos): ?><table><thead><tr><th>Descrição</th><th>Marca / modelo</th><th>Serial</th><th>Hostname</th><th>Patrimônio</th></tr></thead><tbody><?php foreach ($equipamentos as $item): ?><tr><td><?= h(ucfirst($item['tipo'] ?? 'Equipamento')) ?></td><td><?= h(($item['marca'] ?? '') . ' ' . ($item['modelo'] ?? '')) ?></td><td><?= h($item['serial'] ?? '—') ?></td><td><?= h($item['hostname'] ?? '—') ?></td><td><?= h($item['patrimonio'] ?? '—') ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><p>Nenhum equipamento incluído.</p><?php endif; ?>
<?php if ($linhas): ?><h2>Linhas vinculadas</h2><table><thead><tr><th>Número</th><th>Tipo</th><th>Centro de custo</th></tr></thead><tbody><?php foreach ($linhas as $linha): ?><tr><td><?= h($linha['numero']) ?></td><td><?= ($linha['tipo'] ?? '') === 'echip' ? 'eSIM' : 'Chip físico' ?></td><td><?= h($linha['centro_custo'] ?? '—') ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?>
<?php if ($tipo === 'devolucao'): ?><div class="term-checks"><h2>Conferência na devolução</h2><p>☐ Em perfeito estado &nbsp; ☐ Apresentando defeito &nbsp; ☐ Faltando peça ou acessório</p></div><?php endif; ?>
<h2>Estado de conservação e observações</h2><div class="term-notes"><?= h($observacoes ?: '____________________________________________________________________________') ?></div><p><?= h($local ?: 'Local: ______________________________') ?>, <?= date('d/m/Y') ?>.</p><div class="term-signatures"><p><?= h($colaborador['nome']) ?><br>Colaborador</p><p>Responsável <?= $tipo === 'entrega' ? 'pela entrega' : 'pelo recebimento' ?><br>Nome: __________________________</p></div><div class="term-footer">AmorSaúde · <?= $tipo === 'entrega' ? 'Entrega' : 'Devolução' ?> de equipamentos · <?= date('d/m/Y') ?></div></main></body></html>
<?php return ob_get_clean();
}
