<?php
session_start();
require_once dirname(__DIR__, 2) . '/includes/auditoria.php';
orionRegistrarAtividade();
if (!isset($_SESSION['usuario_id'])) { header('Location: ../../index.php'); exit; }
date_default_timezone_set('America/Sao_Paulo');
$base = dirname(__DIR__, 2);
require __DIR__ . '/servico.php';
function h($valor): string { return htmlspecialchars((string)($valor ?? ''), ENT_QUOTES, 'UTF-8'); }
$statusNomes = ['aguardando_envio' => 'Aguardando envio', 'em_manutencao' => 'Em manutenção', 'concluido' => 'Concluído'];
$erro = ''; $pessoas = $ativos = $listas = $solicitacoes = [];
try {
    foreach (['ativos', 'inativos', 'terceiros'] as $grupo) foreach (manutencaoLer($base . '/data/colaboradores/' . $grupo . '.json') as $pessoa) { $pessoas[(string)$pessoa['id']] = $pessoa; if ($grupo !== 'inativos') $ativos[(string)$pessoa['id']] = $pessoa; }
    $listas = manutencaoInventario($base); $solicitacoes = manutencaoLer($base . '/data/solicitacoes_manutencao/solicitacoes.json');
} catch (Throwable $e) { $erro = 'Não foi possível carregar os dados da pasta /data.'; }
if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$erro) {
    try {
        if (!hash_equals($_SESSION['manutencao_csrf'] ?? '', (string)($_POST['csrf'] ?? '')) || empty($_SESSION['manutencao_csrf'])) throw new RuntimeException('Sessão inválida. Atualize a página.');
        $_SESSION['manutencao_mensagem'] = manutencaoExecutar($base, $_POST, $ativos);
        header('Location: manutencao.php'); exit;
    } catch (Throwable $e) { $erro = $e instanceof RuntimeException ? $e->getMessage() : 'Não foi possível salvar a solicitação.'; }
}
$_SESSION['manutencao_csrf'] ??= bin2hex(random_bytes(32));
$idPessoa = (string)($_GET['colaborador_id'] ?? ''); $busca = trim((string)($_GET['busca'] ?? '')); $statusFiltro = (string)($_GET['status'] ?? 'ativas');
$itens = []; $porId = [];
foreach ($listas as $fonte => $lista) foreach ($lista as $item) { $item['_chave'] = $fonte . ':' . $item['id']; $itens[] = $item; $porId[(string)$item['id']] = $item; }
$opcoes = array_values(array_filter($itens, fn($item) => ($idPessoa === '' || (string)($item['colaborador_id'] ?? '') === $idPessoa) && ($busca === '' || stripos(($item['patrimonio'] ?? '') . ' ' . ($item['hostname'] ?? '') . ' ' . ($item['marca'] ?? '') . ' ' . ($item['modelo'] ?? ''), $busca) !== false)));
$chave = (string)($_POST['equipamento'] ?? $_GET['equipamento'] ?? ''); $selecionado = null; foreach ($itens as $item) if ($item['_chave'] === $chave) $selecionado = $item;
$exibidas = array_values(array_filter($solicitacoes, function($s) use ($idPessoa, $busca, $statusFiltro, $porId) {
    $equip = $porId[(string)($s['equipamento_relacionado_id'] ?? '')] ?? [];
    $pessoa = (string)($s['colaborador_id'] ?? $equip['colaborador_id'] ?? '');
    return ($idPessoa === '' || $pessoa === $idPessoa) && ($busca === '' || stripos(($s['patrimonio'] ?? '') . ' ' . ($equip['hostname'] ?? '') . ' ' . ($equip['modelo'] ?? ''), $busca) !== false) && ($statusFiltro === 'todas' || ($statusFiltro === 'ativas' ? $s['status'] !== 'concluido' : $s['status'] === $statusFiltro));
}));
usort($exibidas, fn($a,$b) => (int)$b['id'] <=> (int)$a['id']); uasort($pessoas, fn($a,$b) => strcasecmp($a['nome'], $b['nome'])); uasort($ativos, fn($a,$b) => strcasecmp($a['nome'], $b['nome']));
$mensagem = $_SESSION['manutencao_mensagem'] ?? ''; unset($_SESSION['manutencao_mensagem']);
?>
<!doctype html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Manutenção - Orion Inventory</title><link rel="stylesheet" href="../../assets/css/global/import.css"><link rel="stylesheet" href="../../assets/css/pages/dashboard.css"><link rel="stylesheet" href="../../assets/css/pages/equipamentos.css"><link rel="stylesheet" href="../../assets/css/pages/manutencao.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><script src="../../assets/js/equipamentos.js" defer></script><script src="../../assets/js/manutencao.js" defer></script></head><body>
<header>
<nav class="menu-lateral"><div class="btn-expandir"><i class="bi bi-card-list"></i></div><ul>
<li class="item-menu"><a href="../dashbord/dashbord.php"><span class="item"><i class="bi bi-columns-gap"></i></span><span class="txt-link">Dashboard</span></a></li>
<li class="item-menu"><a href="../colaboradores/colaboradores.php"><span class="item"><i class="bi bi-person"></i></span><span class="txt-link">Colaboradores</span></a></li>
<li class="item-menu"><a href="../equipamentos/equipamentos.php"><span class="item"><i class="bi bi-pc-display-horizontal"></i></span><span class="txt-link">Equipamentos</span></a></li>
<li class="item-menu"><a href="../linhas/linhas.php"><span class="item"><i class="bi bi-sd-card"></i></span><span class="txt-link">Linhas</span></a></li>
<li class="item-menu"><a href="../termos/termos.php"><span class="item"><i class="bi bi-file-earmark-pdf"></i></span><span class="txt-link">Termos</span></a></li>
<li class="item-menu active"><a href="manutencao.php" aria-current="page"><span class="item"><i class="bi bi-tools"></i></span><span class="txt-link">Manutenção</span></a></li>
<li class="item-menu"><a href="../chamado/chamado.php"><span class="item"><i class="bi bi-headset"></i></span><span class="txt-link">Chamado</span></a></li>
<li class="item-menu"><a href="#"><span class="item"><i class="bi bi-person-circle"></i></span><span class="txt-link">Usuários</span></a></li>
</ul></nav>
<div class="logo"><a href="../dashbord/dashbord.php"><img src="../../img/global/logos/orion" alt="Orion Inventory"></a></div>
<div class="usuario-menu"><span class="usuario-nome"><i class="fas fa-user-shield"></i> <?php echo htmlspecialchars($_SESSION['usuario_nome'] ?? 'Usuário'); ?></span></div>
<a href="../../logout.php" class="sair-btn"><i class="fas fa-sign-out-alt"></i><span>Sair</span></a>
</header>
<main class="equipment-page maintenance-page"><div class="equipment-heading"><div><h1><i class="fas fa-tools" aria-hidden="true"></i> Manutenção</h1><p>Acompanhe os reparos internos e externos dos equipamentos.</p></div></div>
<?php if ($erro): ?><p class="equipment-notice equipment-error" role="alert"><?= h($erro) ?></p><?php endif; ?><?php if ($mensagem): ?><p class="equipment-notice" role="status"><?= h($mensagem) ?></p><?php endif; ?>
<section class="equipment-filters"><h2>Colaborador / equipamento</h2><form method="get"><label class="equipment-collaborator-field" data-collaborator-combobox data-collaborator-filter>Colaborador<select name="colaborador_id"><option value="">Todos os colaboradores</option><?php foreach ($pessoas as $pessoa): ?><option value="<?= h($pessoa['id']) ?>" <?= $idPessoa === (string)$pessoa['id'] ? 'selected' : '' ?>><?= h($pessoa['nome'] . ' · ' . ($pessoa['departamento'] ?? '')) ?></option><?php endforeach; ?></select></label><label>Equipamento / patrimônio<input name="busca" value="<?= h($busca) ?>" placeholder="Patrimônio, hostname, marca ou modelo"></label><label>Status<select name="status"><option value="ativas" <?= $statusFiltro === 'ativas' ? 'selected' : '' ?>>Solicitações ativas</option><option value="todas" <?= $statusFiltro === 'todas' ? 'selected' : '' ?>>Todas</option><?php foreach ($statusNomes as $valor => $rotulo): ?><option value="<?= $valor ?>" <?= $statusFiltro === $valor ? 'selected' : '' ?>><?= $rotulo ?></option><?php endforeach; ?></select></label><button class="equipment-primary" type="submit">Buscar</button><a class="equipment-secondary" href="manutencao.php">Limpar</a></form>
<form method="get" class="maintenance-load"><input type="hidden" name="colaborador_id" value="<?= h($idPessoa) ?>"><input type="hidden" name="busca" value="<?= h($busca) ?>"><input type="hidden" name="status" value="<?= h($statusFiltro) ?>"><label class="equipment-collaborator-field" data-equipment-combobox>Equipamento<select name="equipamento" class="equipment-type-select" required><option value="">Selecione um equipamento</option><?php foreach ($opcoes as $item): ?><option value="<?= h($item['_chave']) ?>" data-patrimonio="<?= h($item['patrimonio'] ?? '') ?>" <?= $chave === $item['_chave'] ? 'selected' : '' ?>><?= h(($item['marca'] ?? '') . ' ' . ($item['modelo'] ?? '') . ' · Patrimônio ' . ($item['patrimonio'] ?? '—') . ' · ' . ($item['hostname'] ?? ucfirst($item['tipo'] ?? ''))) ?></option><?php endforeach; ?></select></label><button class="equipment-primary" type="submit">Carregar</button></form></section>
<?php if ($selecionado): ?><section class="equipment-form-panel"><div class="maintenance-equipment"><i class="fas fa-<?= in_array($selecionado['tipo'] ?? '', ['notebook','desktop'], true) ? 'laptop' : 'tools' ?>" aria-hidden="true"></i><div><h2><?= h(($selecionado['marca'] ?? '') . ' ' . ($selecionado['modelo'] ?? '')) ?></h2><p>Patrimônio <?= h($selecionado['patrimonio'] ?? '—') ?> · Serial <?= h($selecionado['serial'] ?? '—') ?> · <?= h($selecionado['hostname'] ?? '') ?></p><p>Colaborador: <?= h($pessoas[(string)($selecionado['colaborador_id'] ?? '')]['nome'] ?? 'Sem alocação') ?> · Status: <?= h(str_replace('_',' ', $selecionado['status'] ?? '')) ?></p></div></div>
<?php if (!in_array($selecionado['status'] ?? '', ['manutencao','fora_uso','pendente_devolucao'], true)): ?><form method="post" class="equipment-form" data-maintenance-open><input type="hidden" name="csrf" value="<?= h($_SESSION['manutencao_csrf']) ?>"><input type="hidden" name="acao" value="abrir"><input type="hidden" name="equipamento" value="<?= h($chave) ?>"><label>Modalidade<select name="modalidade" class="equipment-type-select" required><option value="interna" <?= ($_POST['modalidade'] ?? '') === 'interna' ? 'selected' : '' ?>>Manutenção interna</option><option value="externa" <?= ($_POST['modalidade'] ?? '') === 'externa' ? 'selected' : '' ?>>Manutenção externa</option></select></label><label data-maintenance-vendor>Prestador / responsável externo<input name="destino_reparo" maxlength="255" value="<?= h($_POST['destino_reparo'] ?? '') ?>" placeholder="Nome do técnico ou assistência"></label><label>Prioridade<select name="prioridade"><option value="normal">Normal</option><option value="baixa">Baixa</option><option value="alta">Alta</option><option value="urgente">Urgente</option></select></label><label class="equipment-form-wide">Descrição do problema<textarea name="descricao_problema" rows="4" maxlength="5000" required><?= h($_POST['descricao_problema'] ?? '') ?></textarea></label><div class="equipment-form-wide maintenance-actions"><button class="equipment-primary" type="submit">Abrir manutenção</button><span>A externa começa aguardando envio; a interna começa em manutenção.</span></div></form><?php else: ?><p>Este equipamento não pode iniciar uma nova manutenção no status atual.</p><?php endif; ?></section><?php endif; ?>
<section class="equipment-list"><div class="equipment-list-heading"><h2>Solicitações de manutenção</h2><span><?= count($exibidas) ?> solicitações</span></div><?php if (!$exibidas): ?><div class="equipment-empty"><i class="fas fa-tools" aria-hidden="true"></i><p>Nenhuma solicitação encontrada.</p></div><?php endif; ?>
<?php foreach ($exibidas as $s): $equip = $porId[(string)($s['equipamento_relacionado_id'] ?? '')] ?? []; $modalidade = $s['modalidade'] ?? 'externa'; ?><article class="maintenance-card"><div class="maintenance-card-heading"><div class="maintenance-icon"><i class="fas fa-tools" aria-hidden="true"></i><strong>#<?= h($s['id']) ?></strong></div><div><strong><?= h(($equip['marca'] ?? '') . ' ' . ($equip['modelo'] ?? ucfirst($s['tipo_equipamento'] ?? 'Equipamento'))) ?></strong><small>Patrimônio <?= h($s['patrimonio'] ?? '—') ?> · <?= $modalidade === 'interna' ? 'Interna' : 'Externa' ?> · <?= h($s['destino_reparo'] ?? '—') ?></small><small><?= h($s['colaborador_nome'] ?? $pessoas[(string)($s['colaborador_id'] ?? $equip['colaborador_id'] ?? '')]['nome'] ?? 'Sem colaborador') ?></small></div><span class="maintenance-status maintenance-status-<?= h(isset($statusNomes[$s['status']]) ? $s['status'] : 'outro') ?>"><?= h($statusNomes[$s['status']] ?? $s['status']) ?></span><time><?= h(date('d/m/Y', strtotime($s['data_envio']))) ?></time></div><details <?= ($_POST['id'] ?? '') === (string)$s['id'] ? 'open' : '' ?>><summary>Detalhes / ações</summary><p class="maintenance-description"><?= h($s['descricao_problema']) ?></p><p>Prioridade: <?= h(ucfirst($s['prioridade'] ?? 'normal')) ?> · Responsável: <?= h($s['responsavel_envio'] ?? '—') ?></p>
<?php if ($s['status'] === 'aguardando_envio'): ?><form method="post" class="maintenance-start"><input type="hidden" name="csrf" value="<?= h($_SESSION['manutencao_csrf']) ?>"><input type="hidden" name="acao" value="iniciar"><input type="hidden" name="id" value="<?= h($s['id']) ?>"><button class="equipment-primary" type="submit">Confirmar envio / iniciar reparo</button></form><?php endif; ?>
<?php if ($s['status'] !== 'concluido'): ?><form method="post" class="equipment-form maintenance-finish" data-maintenance-finish data-confirm="Concluir a manutenção e mover o equipamento para o destino selecionado?"><input type="hidden" name="csrf" value="<?= h($_SESSION['manutencao_csrf']) ?>"><input type="hidden" name="acao" value="concluir"><input type="hidden" name="id" value="<?= h($s['id']) ?>"><label>Destino após o reparo<select name="destino_conclusao" class="equipment-type-select" required><option value="estoque">Inventário</option><option value="interno">Uso interno</option><option value="fora_uso">Fora de uso</option><option value="alocado">Alocar a colaborador</option></select></label><label class="equipment-collaborator-field" data-collaborator-combobox data-maintenance-collaborator>Colaborador<select name="colaborador_id"><option value="">Selecione um colaborador</option><?php foreach ($ativos as $pessoa): ?><option value="<?= h($pessoa['id']) ?>"><?= h($pessoa['nome'] . ' · ' . ($pessoa['departamento'] ?? '')) ?></option><?php endforeach; ?></select></label><label class="equipment-form-wide">Resultado do reparo<textarea name="solucao" rows="3" maxlength="5000" required><?= ($_POST['id'] ?? '') === (string)$s['id'] ? h($_POST['solucao'] ?? '') : '' ?></textarea></label><div class="equipment-form-wide"><button class="equipment-primary" type="submit">Concluir manutenção</button></div></form><?php else: ?><p class="maintenance-description"><strong>Resultado:</strong> <?= h($s['solucao'] ?? 'Conclusão registrada no banco anterior.') ?></p><p>Destino: <?= h($s['destino_conclusao'] ?? '—') ?> · Concluído em <?= h(date('d/m/Y H:i', strtotime($s['data_conclusao']))) ?></p><?php endif; ?><details class="maintenance-history"><summary>Histórico de status</summary><?php foreach (($s['historico_status'] ?? []) as $historico): ?><p><?= h(date('d/m/Y H:i', strtotime($historico['data']))) ?> · <?= h($statusNomes[$historico['status']] ?? $historico['status']) ?> · <?= h($historico['usuario'] ?? '—') ?></p><?php endforeach; ?></details></details></article><?php endforeach; ?></section></main><footer><p>Orion Inventory © 2023 - 2026 - Todos os direitos reservados</p></footer></body></html>
